### ISSUE TITLE
Nexus S Suggestions

### ISSUE THREAD

**Issue by jonashendrickx** [edoko/AIR-Kernel_ICS#1]
Can you add more frequencies to the nexus s? Or at least consider 600mhz?

Then we have 100-200-400-600-800-1000-1200-1400

Each at approximately 950mv-950-1025-1100-1175-1250-1325-1400 arm millivolt
This stepping would be perfect.

Or a 100mhz stepping up to 1400mhz

**Comment by biergaizi** [comment]
Please use LiveOC overclock method. You can do it with NSTools.
